FROM steemitinc/ci-test-environment:latest

ADD . /usr/local/src/steem

RUN \
    cd /usr/local/src/steem && \
    git submodule update --init --recursive && \
    mkdir build && \
    cd build && \
    cmake \
        -DCMAKE_BUILD_TYPE=Debug \
        -DBUILD_STEEM_TESTNET=ON \
        -DLOW_MEMORY_NODE=OFF \
        -DCLEAR_VOTES=ON \
        .. && \
    make -j$(nproc) VERBOSE=1 chain_test && \
    ./tests/chain_test && \
    cd /usr/local/src/steem && \
    doxygen && \
    programs/build_helpers/check_reflect.py
